### ISSUE TITLE
[docker] Jupyter notebook demonstrating integration workflows

### ISSUE THREAD

**Issue by jastier** [ml4ai/ASKEM-TA1-DockerVM#19]
## Docker image with notebooks

```[tasklist]
### Tasks
- [x] Add Jupyter support in a skema image (if not already present)
- [x] Add example notebooks to https://github.com/ml4ai/ASKEM-TA1-DockerVM (see  https://github.com/ml4ai/skema/tree/main/notebooks for examples)
```

Relates to ml4ai/skema#213

**Comment by myedibleenso** [comment]
Add the following higher-level REST endpoints to create for TA-1 Service Architecture:

SKEMA-side:
- [ ] [PDF(s)] to [TR Extractions]
  - orchestrates call to UWisc COSMOS
- [ ] [Code + optional PDF(s) + PN,RegNet choice] to [AMR+metadata]
  - supports: model extraction from code
- [ ] [AMR + PDF(s) + PN,RegNet choice] to [AMR+metadata]
  - supports: model metadata enrichment
- [ ] [Eqn (image, latex, MathML) + PN,RegNet choice] to [AMR (PN, RegNet)]
  - supports: model curation

MIT-side:
- [ ] [Dataset headers + PDF(s)] to [Data+Metadata/DKGgrounding (Terrarium DataSheet template)]
  - supports: dataset metadata enrichment
 
[architecture-TA1-service.pdf [SKEMA google drive]](https://drive.google.com/file/d/1ad13Cpjyf8wcSmJUd27KzV1vHZuXLG25/view?usp=sharing)

**Comment by enoriega** [comment]
I think this should go under https://github.com/ml4ai/ASKEM-TA1-DockerVM
