### ISSUE TITLE
Update Notebook Examples

### ISSUE THREAD

**Issue by Free-Quarks** [ml4ai/ASKEM-TA1-DockerVM#48]
There are a few notebooks we have with examples of using our endpoints. However I think they are probably outdated at this point. We should make sure they get updated before the program ends so they are still valid documentation. This issue is to remind us and track that work. 

- [ ] eq2amr endpoints updated
- [x] #53
- [ ] image2mml endpoints updated
- [ ] isa endpoints updated
- [x] text-reading endpoints updated

We should also make sure the README is up to date as well with respect to these endpoints. 

- [ ] eq2amr endpoints updated
- [x] code2amr endpoints updated
- [ ] image2mml endpoints updated
- [ ] isa endpoints updated
- [x] text-reading endpoints updated
```[tasklist]
### Tasks
```
