### ISSUE TITLE
[code2fn] Add `end-to-end-rest` example for processing source code

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/ASKEM-TA1-DockerVM#5]
In coordination with @vincentraymond-ua , add add code2FN notebooks to `code2fn-rest` example.
```[tasklist]
### Tasks
- [ ] https://github.com/ml4ai/ASKEM-TA1-DockerVM/issues/7
- [ ] https://github.com/ml4ai/ASKEM-TA1-DockerVM/issues/8
- [ ] https://github.com/ml4ai/skema/issues/238
- [ ] https://github.com/ml4ai/skema/issues/285
```

**Comment by myedibleenso** [comment]
Completed around the time of the hackathon.
